import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'; // or `v14-appRouter` if 
import GlobalStyles from "@mui/material/GlobalStyles";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (

        <html lang="en">
            <body>
                <GlobalStyles
                    styles={{
                        body: { margin: 0 }
                    }}
                />
                <AppRouterCacheProvider>
                    {children}
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
